[package]
name = "sim-native-bench"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bench"
path = "src/main.rs"

[dependencies]
sim-native-des = { path = "../des" }
sim-native-monte = { path = "../monte" }
serde_json = "1.0"

